/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.turing.javase6.dao.ui;

import com.turing.javase6.dao.ActorDao;
import com.turing.javase6.dao.ActorInMovieDao;
import com.turing.javase6.dao.MovieDao;
import com.turing.javase6.dao.entity.Actor;
import com.turing.javase6.dao.entity.Movie;
import com.turing.javase6.dao.impl.ActorDaoImpl;
import com.turing.javase6.dao.impl.ActorInMovieDaoImpl;
import com.turing.javase6.dao.impl.MovieDaoImpl;
import com.turing.javase6.dao.service.ActorService;
import com.turing.javase6.dao.service.ActorServiceImpl;
import com.turing.javase6.dao.service.MovieActorAssignmentService;
import com.turing.javase6.dao.service.MovieActorAssignmentServiceImpl;
import com.turing.javase6.dao.service.MovieService;
import com.turing.javase6.dao.service.MovieServiceImpl;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class MovieActorAssignment extends javax.swing.JFrame {
    MovieService movieService = new MovieServiceImpl();
    ActorService actorService = new ActorServiceImpl();
    MovieActorAssignmentService movieActorAssignmentService = new MovieActorAssignmentServiceImpl();
    
    ArrayList<Movie> movies = new ArrayList<>();
    ArrayList<Actor> actors = new ArrayList<>();
    /**
     * Creates new form MovieActorAssignment
     */
    public MovieActorAssignment() {
        initComponents();
        this.loadAllMovie();
        this.loadAllActor();
    }
    void loadAllMovie()
    {
        List<Movie> movies = this.movieService.getAllMovie();
        for(Movie movie : movies)
        {
            this.movies.add( movie);
            this.cboMovie.addItem(movie.title());
        }
    }
    void loadAllActor()
    {
        List<Actor>actors = this.actorService.getAllActor();
        for(Actor actor : actors)
        {
            this.actors.add( actor);
            this.cboActor.addItem(actor.name());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMovie = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboActor = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();

        jLabel1.setText("Movie");

        jLabel2.setText("Actor");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssign)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cboMovie, 0, 401, Short.MAX_VALUE)
                        .addComponent(cboActor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cboActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAssign)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        System.out.println("Assignment");
        assignActorToMovie();
    }//GEN-LAST:event_btnAssignActionPerformed
    public void assignActorToMovie()
    {
        int movieIndex = this.cboMovie.getSelectedIndex();
        int actorIndex= this.cboActor.getSelectedIndex();
        
        Movie movie = this.movies.get(movieIndex);
        Actor actor = this.actors.get(actorIndex);
        
        System.out.println("Movie "+movie + " Actor "+actor);
        this.movieActorAssignmentService.addActorToMovie(movie.id(), actor.id());
        JOptionPane.showMessageDialog(this, "Actor have been successfully assigened to movie");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieActorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieActorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieActorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieActorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieActorAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox<String> cboActor;
    private javax.swing.JComboBox<String> cboMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
